PrincipalApp/urls.py
from django.urls import path
from PrincipalApp import views 
from django.contrib.auth.decorators import login_required 


app_name = 'Store'
urlpatterns = [
    
    path('modales/',views.modales,name='modales'), 

    path('inicio_major/',views.inicio_major,name='inicio_major'),  
    path('refresh_cart/',views.refresh_cart,name='refresh_cart'),
   

    path('cart/', views.cart, name='cart'), 
  
    path('limpiar/', views.limpiar_carrito, name="CLS"),

    path('',views.InicioView.as_view(),name='Inicio'),   
    path('ProductDetail/<int:pk>/',views.ProductDetail.as_view(),name='ProductDetail'),   
    path('RegisterUser/',views.RegisterUser.as_view(),name='RegisterUser'),   
    path('Login/',views.Login.as_view(),name='Login'),   
    path('Logout/',views.Logout.as_view(),name='Logout'),  
    path('MyAccount/',views.MyAccount.as_view(),name='MyAccount'),   
 
    path('ShoppingCart/',views.ShoppingCart.as_view(),name='ShoppingCart'),      

    path('ContactUs/',views.ContactUs.as_view(),name='ContactUs'), 

    path('Shop/',views.Shop.as_view(),name='Shop'), 

    path('Search/',views.Search,name='Search'),    
]

Store/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('PrincipalApp.urls'))  ,
    path('',include('DashboardApp.urls'))  ,
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

templates/Major/ContactUs.html
{% extends "Layouts/BaseMajor.html" %}
{% load static %}

{% block title %}
 Alppha
{% endblock %}


{% block css %} 
 
{% endblock %}

{% block content %} 

<div class="banner-title-section container mx-auto px-2 sm:px-8 my-5">
    <div class="liner-container flex justify-center border-b-2 border-[rgba(119,119,119,.17)] my-5">
        <h1 class="uppercase text-2xl font-bold inline-block border-b-2 border-primary-color mb-[-2px] pb-3">Contact Us</h1>
    </div>
</div>

<div class="information-section container mx-auto px-2 sm:px-8 my-5">
    <div class="grid grid-cols-12 gap-5">
        {% for item in business%}
        <div class="col-span-12 sm:col-span-6 lg:col-span-3 flex">
            <div class="flex items-center w-full gap-4 p-5 xs:pl-[20%] sm:pl-5 rounded-lg bg-white hover:shadow-lg transition-all-300">
                <div class="rounded-full border-2">
                    <i class="bi bi-telephone text-primary-color text-[40px] p-3 flex"></i>
                </div>
                <div>
                    <h6 class="font-bold capitalize">Phone</h6>
                    <p class="text-sm text-gray-400 break-all">{{item.phone}}</p>
                </div>
            </div>
        </div>
        <div class="col-span-12 sm:col-span-6 lg:col-span-3 flex">
            <div class="flex items-center w-full gap-4 p-5 xs:pl-[20%] sm:pl-5 rounded-lg bg-white hover:shadow-lg transition-all-300">
                <div class="rounded-full border-2">
                    <i class="bi bi-envelope text-primary-color text-[40px] p-3 flex"></i>
                </div>
                <div>
                    <h6 class="font-bold capitalize">E-mail</h6>
                    <p class="text-sm text-gray-400 break-all">{{item.email}}</p>
                </div>
            </div>
        </div>
        <div class="col-span-12 sm:col-span-6 lg:col-span-3 flex">
            <div class="flex items-center w-full gap-4 p-5 xs:pl-[20%] sm:pl-5 rounded-lg bg-white hover:shadow-lg transition-all-300">
                <div class="rounded-full border-2">
                    <i class="bi bi-geo-alt text-primary-color text-[40px] p-3 flex"></i>
                </div>
                <div>
                    <h6 class="font-bold capitalize">Ubication</h6>
                    <p class="text-sm text-gray-400 break-all">{{item.address}}</p>
                </div>
            </div>
        </div>
        <div class="col-span-12 sm:col-span-6 lg:col-span-3 flex">
            <div class="flex items-center w-full gap-4 p-5 xs:pl-[20%] sm:pl-5 rounded-lg bg-white hover:shadow-lg transition-all-300">
                <div class="rounded-full border-2">
                    <i class="bi bi-clock text-primary-color text-[40px] p-3 flex"></i>
                </div>
                <div>
                    <h6 class="font-bold capitalize">Hours</h6>
                    <p class="text-sm text-gray-400 break-all">Monday to Friday 8:00 to 18:00</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="leave-message-section container mx-auto px-2 sm:px-8 my-5">
    <div class="grid grid-cols-12 rounded-lg overflow-hidden">
        <div class="col-span-12 sm:col-span-6 h-60 sm:h-full">
            <iframe class="w-full h-full" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25525.690009671285!2d-60.3206370790762!3d-36.88856868458139!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x959445daae9e90a3%3A0xd11aadb313dbf072!2sOlavarr%C3%ADa%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1ses!2sar!4v1643148990997!5m2!1ses!2sar" width="700" height="500" style="border: 0" allowfullscreen="" loading="lazy"></iframe>
        </div>
        <div class="col-span-12 sm:col-span-6 bg-white p-5">
            <h1 class="uppercase text-xl font-bold inline-block pb-3">Leave a Message</h1>
            <form class="form-leave-message flex flex-col gap-5" action="javascript:void(0)">
                <div>
                    <input class="input" type="text" placeholder="Your Name" required />
                </div>
                <div>
                    <input class="input" type="email" placeholder="Your E-mail" required />
                </div>
                <div class="h-32">
                    <textarea class="input h-full resize-none" placeholder="Write your message here..." required></textarea>
                </div>
                <div>
                    <button class="btn-view-shopping-cart btn-effect flex justify-center items-center p-4 bg-primary-color rounded-lg transition-all-300" type="submit">
                        <span class="font-bold uppercase text-white">Send Message</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


 

{% endblock %}


{% block extrajs %}  
 

{% endblock extrajs %}

templates/Major/Index.html
{% extends "Layouts/BaseMajor.html" %}
{% load static %}

{% block title %}
 Alppha
{% endblock %}


{% block css %} 

 
{% endblock %}

{% block content %} 

<div class="banners-section container mx-auto px-2 sm:px-8 my-5">
	<div class="grid grid-cols-12 gap-5">
		<div class="swiper-container col-span-12 md:col-span-8 rounded-lg overflow-hidden">
			<div class="swiper swiper-banner group relative flex items-center">
				<div class="swiper-wrapper max-h-[377px]">
					<div class="swiper-slide">
						<img src="/static/store/img/banner/banner-1.jpg" alt="banner 1" />
					</div>
					<div class="swiper-slide">
						<img src="/static/store/img/banner/banner-2.jpg" alt="banner 2" />
					</div>
					<div class="swiper-slide">
						<img src="/static/store/img/banner/banner-3.jpg" alt="banner 3" />
					</div>
				</div>
				<div class="button-next btn-slider-1 -right-16 transition-all-300 group-hover:right-4">&#10095;</div>
				<div class="button-prev btn-slider-1 -left-16 transition-all-300 group-hover:left-4">&#10094;</div>
				<div class="swiper-pagination"></div>
			</div>
		</div>
		<div class="hidden md:block col-span-4 rounded-lg overflow-hidden relative group">
			<div class="overlay-gradient absolute h-full w-full z-[1]"></div>
			<img class="w-full h-full object-cover transition-all-300 hover:transform group-hover:scale-110" src="/static/store/img/categories/sec-desktop-g.jpg" alt="banner-img" />
			<div class="absolute top-0 left-0 flex items-center h-full w-full">
				<div class="p-5 z-[2]">
					<h3 class="uppercase text-lg font-bold text-primary-color drop-shadow-xl">Armed pc gamer</h3>
					<p class="text-white my-5 drop-shadow-md">Choose your pc and play!</p>
					<a class="btn-effect inline-block text-white bg-primary-color rounded-lg py-2 px-3" href="#">
						<span>Shop now</span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="information-section container mx-auto px-2 sm:px-8 my-5">
	<div class="grid grid-cols-12 gap-5">
		<div class="col-span-12 sm:col-span-6 lg:col-span-3 flex">
			<div class="flex items-center w-full gap-4 p-5 xs:pl-[20%] sm:pl-5 rounded-lg bg-white hover:shadow-lg transition-all-300">
				<div class="rounded-full border-2">
					<i class="bi bi-truck text-primary-color text-[40px] p-3 flex"></i>
				</div>
				<div>
					<h6 class="font-bold capitalize">Free shipping</h6>
					<p class="text-sm text-gray-400 break-all">Orders over $100</p>
				</div>
			</div>
		</div>
		<div class="col-span-12 sm:col-span-6 lg:col-span-3 flex">
			<div class="flex items-center w-full gap-4 p-5 xs:pl-[20%] sm:pl-5 rounded-lg bg-white hover:shadow-lg transition-all-300">
				<div class="rounded-full border-2">
					<i class="bi bi-cash-coin text-primary-color text-[40px] p-3 flex"></i>
				</div>
				<div>
					<h6 class="font-bold capitalize">Money back</h6>
					<p class="text-sm text-gray-400 break-all">With a 30 day</p>
				</div>
			</div>
		</div>
		<div class="col-span-12 sm:col-span-6 lg:col-span-3 flex">
			<div class="flex items-center w-full gap-4 p-5 xs:pl-[20%] sm:pl-5 rounded-lg bg-white hover:shadow-lg transition-all-300">
				<div class="rounded-full border-2">
					<i class="bi bi-shield-check text-primary-color text-[40px] p-3 flex"></i>
				</div>
				<div>
					<h6 class="font-bold capitalize">Secure payment</h6>
					<p class="text-sm text-gray-400 break-all">Secured payment</p>
				</div>
			</div>
		</div>
		<div class="col-span-12 sm:col-span-6 lg:col-span-3 flex">
			<div class="flex items-center w-full gap-4 p-5 xs:pl-[20%] sm:pl-5 rounded-lg bg-white hover:shadow-lg transition-all-300">
				<div class="rounded-full border-2">
					<i class="bi bi-headset text-primary-color text-[40px] p-3 flex"></i>
				</div>
				<div>
					<h6 class="font-bold capitalize">Online support</h6>
					<p class="text-sm text-gray-400 break-all">Support 24/7</p>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="offers-section container mx-auto px-2 sm:px-8 my-5">
	<div class="liner-container flex justify-center border-b-2 border-[rgba(119,119,119,.17)] mt-5">
		<h1 class="uppercase text-2xl font-bold inline-block border-b-2 border-primary-color mb-[-2px] pb-3">Offers</h1>
	</div>
	<div class="swiper-container">
		<div class="swiper swiper-cards group relative flex items-center py-5">
			<div class="swiper-wrapper">
				{% for list in recently %}
				<div class="swiper-slide h-auto">
					<div class="card-container h-full flex flex-col p-5 bg-white rounded-lg shadow-md hover:shadow-xl relative transition-all-300 hover:z-[2] translateY-2 overflow-hidden">
						<div class="absolute top-[10px] right-[10px]">
							<div class="p-[2px]">
								<a onclick="view({{list.id}})" class="tippy tippy-left-card-view btn-open-modal flex justify-center items-center h-9 w-9 bg-[rgba(0,0,0,.3)] hover:bg-primary-hover rounded-lg transition-all-300 cursor-pointer" href="javascript:void(0)" data-target=".quick-view-modal">
									<i class="bi bi-eye text-xl text-white flex pointer-events-none"></i>
								</a>
							</div>
						</div> 
						<div class="h-[190px] overflow-hidden rounded-lg">
							<a href="{% url 'Store:ProductDetail' list.id %}">
								<img class="card-object-fit w-full h-full" src="{{list.get_image}}" alt="product" />
							</a>
						</div>
						<div class="my-2 flex justify-between"> 
							<div>
								{% if list.stock == 0 %}
								<span class="text-xs uppercase font-bold text-black ">outstock</span>										
								{%else %}
								<span class="text-xs uppercase font-bold text-white bg-green-300 py-1 px-2 rounded-md">instock</span>
								{%endif %}
							</div>
						</div>
						<div class="my-1">
							<a class="clamp font-medium break-all" href="#">{{list.name}} </a>
						</div>
						<div class="my-1">
							<p class="text-sm clamp-2 text-gray-400">{{list.descripcion}}</p>
						</div> 
						<div class="my-1">
							<span class="text-lg font-bold">{{list.price}}</span>
							<span class="text-sm text-primary-color line-through">$50.00</span>
						</div>
						<div class="mt-auto">
							<a class="btn-effect flex justify-center items-center w-full p-2 bg-primary-color rounded-lg transition-all-300" 
							href="{% url 'Store:ProductDetail' list.id %}">
								<span class="font-bold uppercase text-white">View details</span>
							</a>
						</div> 
					</div>
				</div>
				{% endfor %}
				 
			</div>
			<div class="button-next btn-slider-1 -right-16 transition-all-300 group-hover:right-4">&#10095;</div>
			<div class="button-prev btn-slider-1 -left-16 transition-all-300 group-hover:left-4">&#10094;</div>
			<div class="swiper-pagination"></div>
		</div>
	</div>
</div>
<div class="banners-section-2 container mx-auto px-2 sm:px-8 my-5">
	<div class="grid grid-cols-12 gap-5">
		<div class="col-span-12 sm:col-span-6 rounded-lg overflow-hidden relative group h-[300px]">
			<div class="overlay-gradient absolute h-full w-full z-[1]"></div>
			<img class="w-full h-full object-cover transition-all-300 hover:transform group-hover:scale-110" src="/static/store/img/categories/sec-notebooks.jpg" alt="banner-img" />
			<div class="absolute top-0 left-0 flex items-center h-full w-full">
				<div class="p-5 z-[2]">
					<h3 class="uppercase text-lg font-bold text-primary-color drop-shadow-xl">Notebooks</h3>
					<p class="text-white my-5 drop-shadow-md">Choose the ideal laptop for you!</p>
					<a class="btn-effect inline-block text-white bg-primary-color rounded-lg py-2 px-3" href="#">
						<span>Show more</span>
					</a>
				</div>
			</div>
		</div>
		<div class="col-span-12 sm:col-span-6 rounded-lg overflow-hidden relative group h-[300px]">
			<div class="overlay-gradient absolute h-full w-full z-[1]"></div>
			<img class="w-full h-full object-cover transition-all-300 hover:transform group-hover:scale-110" src="/static/store/img/categories/sec-desktops.jpg" alt="banner-img" />
			<div class="absolute top-0 left-0 flex items-center h-full w-full">
				<div class="p-5 z-[2]">
					<h3 class="uppercase text-lg font-bold text-primary-color drop-shadow-xl">Desktops</h3>
					<p class="text-white my-5 drop-shadow-md">Build your PC at the best price!</p>
					<a class="btn-effect inline-block text-white bg-primary-color rounded-lg py-2 px-3" href="#">
						<span>Show more</span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="products-1-section container mx-auto px-2 sm:px-8 my-5">
	<div class="liner-container flex justify-center border-b-2 border-[rgba(119,119,119,.17)] mt-5">
		<h1 class="uppercase text-2xl font-bold inline-block border-b-2 border-primary-color mb-[-2px] pb-3">Notebooks</h1>
	</div>
	<div class="grid grid-cols-12 gap-5">
		<div class="col-span-3 rounded-l-lg relative group overflow-hidden hidden xl:block my-5">
			<div class="overlay-gradient absolute h-full w-full z-[1]"></div>
			<img class="w-full h-full object-cover transition-all-300 hover:transform group-hover:scale-110" src="/static/store/img/categories/sliders/notebooks.jpg" alt="banner-img" />
			<div class="absolute top-0 left-0 flex items-center h-full w-full">
				<div class="p-5 z-[2]">
					<h3 class="uppercase text-lg font-bold text-primary-color drop-shadow-xl">Notebooks</h3>
					<p class="text-white my-5 drop-shadow-md">Choose your laptop now!</p>
					<a class="btn-effect inline-block text-white bg-primary-color rounded-lg py-2 px-3" href="#">
						<span>Show more</span>
					</a>
				</div>
			</div>
		</div>
		<div class="col-span-12 xl:col-span-9 cards-slider-2 swiper-container">
			<div class="swiper swiper-cards-2 group relative flex items-center py-5">
				<div class="swiper-wrapper">
					{% for list in price %}
				<div class="swiper-slide h-auto">
					<div class="card-container h-full flex flex-col p-5 bg-white rounded-lg shadow-md hover:shadow-xl relative transition-all-300 hover:z-[2] translateY-2 overflow-hidden">
						<div class="absolute top-[10px] right-[10px]">						 
							<div class="p-[2px]">
								<a onclick="view({{list.id}})" class="tippy tippy-left-card-view btn-open-modal flex justify-center items-center h-9 w-9 bg-[rgba(0,0,0,.3)] hover:bg-primary-hover rounded-lg transition-all-300 cursor-pointer" href="javascript:void(0)" data-target=".quick-view-modal">
									<i class="bi bi-eye text-xl text-white flex pointer-events-none"></i>
								</a>
							</div>
						</div> 
						<div class="h-[190px] overflow-hidden rounded-lg">
							<a href="{% url 'Store:ProductDetail' list.id %}">
								<img class="card-object-fit w-full h-full" src="{{list.get_image}}" alt="product" />
							</a>
						</div>
						<div class="my-2 flex justify-between"> 
							<div>
								{% if list.stock == 0 %}
								<span class="text-xs uppercase font-bold text-black ">outstock</span>										
								{%else %}
								<span class="text-xs uppercase font-bold text-white bg-green-300 py-1 px-2 rounded-md">instock</span>
								{%endif %}
							</div>
						</div>
						<div class="my-1">
							<a class="clamp font-medium break-all" href="#">{{list.name}} </a>
						</div>
						<div class="my-1">
							<p class="text-sm clamp-2 text-gray-400">{{list.descripcion}}</p>
						</div> 
						<div class="my-1">
							<span class="text-lg font-bold">{{list.price}}</span>
							<span class="text-sm text-primary-color line-through">$50.00</span>
						</div>
						<div class="mt-auto">
							<a class="btn-effect flex justify-center items-center w-full p-2 bg-primary-color rounded-lg transition-all-300" 
							href="{% url 'Store:ProductDetail' list.id %}">
								<span class="font-bold uppercase text-white">View details</span>
							</a>
						</div>
					</div>
				</div>
				{% endfor %}
				 
				</div>
				<div class="button-next btn-slider-1 -right-16 transition-all-300 group-hover:right-4">&#10095;</div>
				<div class="button-prev btn-slider-1 -left-16 transition-all-300 group-hover:left-4">&#10094;</div>
				<div class="swiper-pagination"></div>
			</div>
		</div>
	</div>
</div>


{% endblock %}


{% block extrajs %} 

<script src="{% static 'ajax.js'%}"></script>
 
{% endblock extrajs %}

templates/Major/Login.html
{% extends "Layouts/BaseMajor.html" %}
{% load static %}

{% block title %}
 Alppha
{% endblock %}


{% block css %} 
 
{% endblock %}

{% block content %} 


<div class="login-section container mx-auto px-2 sm:px-8 my-5">
    <div class="p-5 bg-white max-w-[500px] rounded-lg mx-auto">
        <div class="my-5">
            <img class="mx-auto" src="img/logo2.png" alt="logo" />
        </div>
        <form method="post"  >
            {% csrf_token %}
            <div class="flex flex-col gap-4">
                <div class="relative flex items-center h-[40px]">
                    <i class="bi bi-person absolute flex ml-2 text-gray-400 text-[24px]"></i>
                    {{ form.username }}
                </div>
                <div class="relative flex items-center h-[40px]">
                    <i class="bi bi-lock absolute flex ml-2 text-gray-400 text-[24px]"></i>
                    {{ form.password }}
                </div>
                <button class="btn-effect h-full w-full p-2 bg-primary-color rounded-lg transition-all-300" type="submit">
                    <span class="font-bold uppercase text-white">Login</span>
                </button>
            </div>
            <div class="flex flex-wrap gap-2 justify-between items-center my-2">
                <label class="flex items-center gap-2 select-none">
                    <input class="checkbox" type="checkbox" />
                    <span class="text-gray-title">Remember</span>
                </label>
                <a class="underlined-animated after:bottom-0 text-[#3091ff]" href="#">Forgot Password?</a>
            </div>
        </form>
        <span class="or text-gray-title py-2 flex items-center h-[50px]">
            <span class="text-sm uppercase mx-2">Or</span>
        </span>
        <div class="flex flex-col sm:flex-row justify-center flex-wrap gap-5">
            <button class="bg-facebook flex justify-center items-center h-[50px] min-w-[100px] rounded-lg hover:scale-110 transition-all-300">
                <i class="bi bi-facebook flex text-white text-3xl"></i>
            </button>
            <button class="bg-twitter flex justify-center items-center h-[50px] min-w-[100px] rounded-lg hover:scale-110 transition-all-300">
                <i class="bi bi-twitter flex text-white text-3xl"></i>
            </button>
            <button class="bg-google flex justify-center items-center h-[50px] min-w-[100px] rounded-lg hover:scale-110 transition-all-300">
                <i class="bi bi-google flex text-white text-3xl"></i>
            </button>
        </div>
        <div class="mt-5 pt-5 flex flex-col justify-center items-center border-t border-t-gray-400">
            <span>Don't have a account?</span>
            <a class="btn-effect text-white rounded-lg bg-primary-color p-2" href="sign-up.html">
                <span>Create one</span>
            </a>
        </div>
    </div>
</div>


{% endblock %}


{% block extrajs %}  

 

{% endblock extrajs %}

templates/Major/ShoppingCart.html
{% extends "Layouts/BaseMajor.html" %}
{% load static %}

{% block title %}
 Alppha
{% endblock %}


{% block css %} 
 
{% endblock %}

{% block content %} 

<div class="breadcrumb-section container mx-auto px-2 sm:px-8 my-5">
    <ul class="flex flex-wrap gap-1 items-center">
        <li class="hover:text-primary-color transition-all-300">
            <a href="{% url 'Store:Inicio' %}">Home</a>
        </li>
        <li>
            <i class="bi bi-caret-right-fill flex text-primary-color"></i>
        </li>
        <li class="hover:text-primary-color transition-all-300 active">
            <a href="{% url 'Store:ShoppingCart' %}">Shopping Cart</a>
        </li>
    </ul>
</div>

<div class="banner-title-section container mx-auto px-2 sm:px-8 my-5">
			<div class="liner-container flex justify-center border-b-2 border-[rgba(119,119,119,.17)] my-5">
				<h1 class="uppercase text-2xl font-bold inline-block border-b-2 border-primary-color mb-[-2px] pb-3">Shopping Cart</h1>
			</div>
		</div>

		<div class="shopping-cart-page container mx-auto px-2 sm:px-8 my-5">
			<!-- If the Shopping Cart is empty (replace hidden with flex) -->
			<div class="shopping-cart-empty hidden flex-col justify-center items-center p-5 gap-4">
				<i class="bi bi-cart-x text-8xl text-gray-200"></i>
				<p class="font-semibold text-lg">There are no products in the cart.</p>
				<a class="btn-effect flex justify-center items-center p-2 bg-primary-color rounded-lg gap-2 transition-all-300" href="#">
					<span class="font-bold uppercase text-white">Go to the store</span>
				</a>
			</div>
			<!-- -->
			<form class="grid grid-cols-12 gap-5 bg-white rounded-lg p-2 xs:p-5"  >
				<div class="col-span-12 lg:col-span-8">
				 
					<!-- Element Desktop -->
					<div class="overflow-x-auto hidden lg:block">
						<table class="w-full min-w-[800px] text-left"  id="data">
							<thead>
								<tr>
									<th></th>
									<th class="p-2">Product Name</th>
									<th class="p-2">Unit Price</th>
									<th class="p-2">Quantity</th>
									<th class="p-2">Subtotal</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<!--{% if request.session.carrito.items %}
								{% for key, value in request.session.carrito.items %}
								<tr class="hover:bg-gray-100">
									<td class="p-2">
										<div class="border rounded-lg h-[100px] w-[100px] min-w-[100px] overflow-hidden">
											<a href="#">
												<img class="w-full h-full object-cover" src="{{value.image}}" alt="product">
											</a>
										</div>
									</td>
									<td class="p-2">
										<a class="font-bold clamp-2 break-all" >{{value.nombre}}</a>
									</td>
									<td class="p-2">
										<span class="font-bold text-primary-color">${{value.price}}</span>
									</td>
									<td class="p-2">
										<div class="quantity inline-flex bg-white rounded-lg shadow">
											<input class="quantity-value input-number w-12 text-center text-lg p-1 bg-transparent text-gray-400 border-none focus:ring-0 focus:border-none" type="number" value="{{value.cantidad}}">
											<div class="flex flex-col justify-between w-5">
												<button onclick="add_cart({{value.producto_id}})" class="quantity-btn increment text-primary-color" type="button"><i class="bi bi-caret-up-fill"></i></button>
												<button onclick="restar_cart({{value.producto_id}})" class="quantity-btn decrement text-primary-color" type="button"><i class="bi bi-caret-down-fill"></i></button>
											</div>
										</div>
									</td>
									<td class="p-2">
										<span class="font-bold text-primary-color"></span>
									</td>
									<td class="p-2">
										<a onclick="delete_cart({{value.producto_id}})" class="tippy tippy-remove btn-delete text-slate-400 hover:text-primary-color transition-all-300">
											<i class="bi bi-trash-fill inline pointer-events-none text-xl"></i>
										</a>
									</td>
								</tr> 
								 
								{% endfor %}
								{% else %}
								<tr>
									<td colspan="3">
										<div class="alert alert-danger text-center"> Sin Productos </div>
									</td>
								</tr>
								{% endif %}-->
                  
							</tbody>
						</table>
					</div>
				</div>
				<div class="col-span-12 lg:col-span-4">  
					<div class="border-2 rounded-lg p-4">
						<span class="font-bold text-lg text-center inline-block mb-10">Summary of your purchase:</span>
						<div class="py-4">
							<div class="flex justify-between my-2">
								<span>Subtotal:</span>
								<span id="subtotal"> </span>
							</div>
							<div class="flex justify-between my-2">
								<span>Iva:</span>
								<span id="iva"></span>
							</div>
							<div class="flex justify-between my-2">
								<span>Shipping:</span>
								<span>$0.00</span>
							</div>
						</div>
						<div class="uppercase flex justify-between font-bold text-xl py-4 border-t-2 border-gray-200">
							<span>Total:</span>
							<span id="total"></span>
						</div>
						<button class="btn-view-shopping-cart btn-effect flex justify-center items-center w-full p-2 bg-primary-color rounded-lg transition-all-300" type="submit">
							<span class="font-bold uppercase text-white">Continue</span>
						</button>
					</div>
					<a class="flex justify-center items-center gap-2 my-5 hover:text-primary-color transition-all-300" href="shopping-cart.html">
						<i class="bi bi-arrow-repeat flex text-xl"></i>
						<span>Update Cart</span>
					</a>
					<a class="flex justify-center items-center gap-2 my-5 hover:text-primary-color transition-all-300" href="shopping-cart.html">
						<i class="bi bi-cart-plus flex text-xl"></i>
						<span>Add more products</span>
					</a>
				</div>
			</form>
		</div> 
{% endblock %}


{% block extrajs %}

<link href="{% static 'bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.css' %}" rel="stylesheet"/>
<script src="{% static 'bootstrap-touchspin-4.3.0/jquery.bootstrap-touchspin.js' %}"></script>
<script src="{% static 'shoppingcart.js'%}"></script> 
 
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.js"></script> 
<script type="application/javascript">
	cart();
    $(function () {
        $('#data').DataTable({
            responsive: true,
            autoWidth: false,
			searching: false, 
            paging: false,
            info: false,  
        });
    }); 
</script>  

{% endblock extrajs %}